export function woodland(arg: any): Woodland;
declare class Woodland extends EventEmitter {
    constructor({ autoindex, cacheSize, cacheTTL, charset, defaultHeaders, digit, etags, indexes, logging, origins, seed, sendError, time }?: {
        autoindex?: boolean;
        cacheSize?: number;
        cacheTTL?: number;
        charset?: string;
        defaultHeaders?: {};
        digit?: number;
        etags?: boolean;
        indexes?: string[];
        logging?: {};
        origins?: string[];
        seed?: number;
        sendError?: boolean;
        time?: boolean;
    });
    autoindex: boolean;
    ignored: Set<any>;
    cache: import("tiny-lru").LRU<any>;
    charset: string;
    corsExpose: string;
    defaultHeaders: any[][];
    digit: number;
    etags: {
        cache: {
            first: any;
            items: any;
            last: any;
            max: number;
            size: number;
            ttl: number;
            has(key: any): boolean;
            clear(): any;
            delete(key: any): any;
            evict(bypass?: boolean): any;
            get(key: any): any;
            keys(): string[];
            set(key: any, value: any, bypass?: boolean): any;
        };
        mimetype: any;
        seed: any;
        create(arg: any): string;
        middleware(req: any, res: any, next: any): void;
        hash(arg?: string, mimetype?: string): string;
        register(key: any, arg: any): any;
        unregister(key: any): void;
        valid(headers: any): boolean;
    };
    indexes: any;
    permissions: import("tiny-lru").LRU<any>;
    logging: {
        enabled: boolean;
        format: any;
        level: any;
    };
    methods: any[];
    middleware: Map<any, any>;
    origins: any;
    sendError: boolean;
    time: boolean;
    allowed(method: any, uri: any, override?: boolean): boolean;
    allows(uri: any, override?: boolean): any;
    always(...args: any[]): Woodland;
    connect(...args: any[]): Woodland;
    clf(req: any, res: any): any;
    decorate(req: any, res: any): void;
    del(...args: any[]): Woodland;
    delete(...args: any[]): Woodland;
    error(req: any, res: any, err: any): void;
    etag(method: any, ...args: any[]): string;
    get(...args: any[]): Woodland;
    ignore(fn: any): Woodland;
    list(method?: string, type?: string): {};
    log(msg: any, level?: string): Woodland;
    onsend(req: any, res: any, body: any, status: any, headers: any): any[];
    options(...args: any[]): Woodland;
    patch(...args: any[]): Woodland;
    path(arg?: string): string;
    post(...args: any[]): Woodland;
    put(...args: any[]): Woodland;
    route(req: any, res: any): void;
    routes(uri: any, method: any, override?: boolean): any;
    serve(req: any, res: any, arg?: string, folder?: string, index?: any): void;
    trace(...args: any[]): Woodland;
    use(rpath: any, ...fn: any[]): Woodland;
}
import { EventEmitter } from "events";
export {};
