---
name: ci

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x, 24.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: npm install

      - name: Test
        run: npm test

      - name: Build
        run: npm run build

  automerge:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: read
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Merge dependabot PR
        uses: fastify/github-action-merge-dependabot@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: minor
          merge-method: squash
